# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

build:
  verbosity: normal

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: https://stackoverflow.com/a/13751649
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\misc\\appveyor\\run_with_env.cmd"
    PYTHON: "C:\\Miniconda-x64"
    CI_URL: "--ci-url https://ci.appveyor.com/project/%APPVEYOR_REPO_NAME%/build/1.0.%APPVEYOR_BUILD_NUMBER%-%APPVEYOR_REPO_BRANCH%"
    PR_URL: "--pr-url https://github.com/%APPVEYOR_REPO_NAME%/pull/%APPVEYOR_PULL_REQUEST_NUMBER%"

  matrix:
    - TARGET_ARCH: "x64"
      CONDA_PY: "2.7"
      PY_CONDITION: "python >=2.7,<3"
      CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"


platform:
  - x64

install:
  # Add miniconda path.
  - "SET PATH=%CONDA_INSTALL_LOCN%\\Scripts;%CONDA_INSTALL_LOCN%\\Library\\bin;%PATH%"
  # Check that we have the expected version and architecture for Python
  - "python --version"
  # Install the build and runtime dependencies of the project.
  - "conda update -q --yes conda"
  # Install default dependencies
  - "conda install --yes pip python=%CONDA_PY% numpy scipy matplotlib cython ipython h5py nose sphinx sympy"
  # - "conda update --yes numpy scipy matplotlib cython ipython h5py nose sphinx sympy"
  # additional dependencies
  - "pip install sphinx_rtd_theme"
  # - "git clone https://github.com/jcapriot/pyMKL.git"
  # - "cd pyMKL"
  # - "python setup.py install"
  # - "cd .."
  # - "git clone https://github.com/rowanc1/pymatsolver.git"
  # - "cd pymatsolver"
  # - "python setup.py install"
  # - "cd .."
  # install SimPEG
  - "python setup.py install"
  - "python setup.py build_ext --inplace"
  # list package versions
  - "conda list"

test_script:
  - "nosetests tests/examples"
