name: simpeg-test
channels:
  - conda-forge
dependencies:
  - numpy>=1.20
  - scipy>=1.8
  - scikit-learn>=1.2
  - pymatsolver>=0.2
  - matplotlib
  - discretize>=0.10
  - geoana>=0.5.0
  - empymod>=2.0.0
  - setuptools_scm
  - pandas
  - dask
  - zarr
  - fsspec
  - jupyter
  - h5py
  - sphinx
  - sphinx-gallery>=0.1.13
  - sphinxcontrib-apidoc
  - pydata-sphinx-theme
  - nbsphinx
  - numpydoc
  - pillow
  - pylint
  - sympy
  - wheel
  - pytest
  - pytest-cov
  - toolz
  - twine
  - memory_profiler
  - plotly
  - pyvista
  - pip
  - python-kaleido
  # Optional dependencies
  - choclo
  # Linters and code style
  - pre-commit
  - black==24.3.0
  - flake8==7.0.0
  - flake8-bugbear==23.12.2
  - flake8-builtins==2.2.0
  - flake8-mutable==1.2.0
  - flake8-rst-docstrings==0.3.0
  - flake8-docstrings==1.7.0
