name : Reviewdog PR Annotations
on: [pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: Flake8 check
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
      - name: Setup Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies to run the flake8 checks
        run: pip install -r requirements_style.txt
      - name: flake8 review
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  black:
    name: Black check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
      - name: Setup Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies to run the black checks
        run: pip install -r requirements_style.txt
      - uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review